version: '3.8'

services:
  sentiment-app:
    build: .
    container_name: sentiment-app-debug
    ports:
      - "8888:5000"
    env_file:
      - docker.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a testing version
  sentiment-app-test:
    build: .
    container_name: sentiment-app-test
    ports:
      - "8889:5000"
    environment:
      - TESTING=true
    restart: unless-stopped
    profiles:
      - test
